### ISSUE TITLE
Error pushing userschema

### ISSUE THREAD

**Issue by savfaire** [ClearBlade/cb-cli#11]
$ cb-cli push -userschema
Pushing user schema
Aborting: User schema could not be updated. Deletion of column(s) failed: Error deleting user column: map[error:map[category:User code:220 detail:You cannot delete cb_service_account column id:ce5126cd-add8-4c5b-8493-f270e599d44c 
level:1 line:clearblade/users/developer_endpoints.go:621 lowLevelError:<nil> message:Internal Server Error] statusCode:500]

**Comment by ms1752** [comment]
@sh3nan1gans this is a pretty straight forward fix in cb-lib. You can see the `michael-temp-fix` branch for the needed changes. Had to push that to unblock Ray on something today.

**Comment by clarkbynum** [comment]
@ms1752 - I did the same thing in https://github.com/ClearBlade/cb-cli/tree/6-3-2020-Jim-found-bugs. I asked @savfaire to test
