### ISSUE TITLE
Trojan detected in 2.13 release for Windows?

### ISSUE THREAD

**Issue by claust** [ClearBlade/cb-cli#3]
_Windows Defender_ warns that Trojan:Win32/Fuerboos.A!cl is detected in cb-cli-2.13-Windows.zip. This means that the file cannot be downloaded using Chrome.

It might be a false positive in which case you can submit the file for analysis at https://www.microsoft.com/en-us/wdsi/filesubmission 

![clearblade](https://user-images.githubusercontent.com/3540940/33654205-aced01a4-da6f-11e7-885c-cf8871414ea3.PNG)

**Comment by rreinold** [comment]
Caused by i386 build, which has been deprecated. Please retest.

**Comment by claust** [comment]
Tada! _Windows Defender_ does not report the 4.2.6 or the 4.3.0-rc1 build as infected. Also, it no longer regards the 2.13 version as suspicious.
